spring:
  datasource:
    url: jdbc:mysql://localhost:3306/home?serverTimezone=CST
    username: root
    password: root
    minimum-idle: 10
    maximum-pool-size: 80
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
server:
  port: 8080
